name: DATAGRAPH
version: 6.7.0

# damap is starboard ELECTRA engine

# qwen3-vl:2b                      0635d9d857d4    1.9 GB    7 hours ago
# AeroCorp/afm:afm-f16             1bc1186d3705    2.0 GB    16 hours ago
# Mostar/remostar-dcx001:latest    acf6bb480c2d    2.2 GB    16 hours ago
# Mostar/mostar-ai:dcx2            51ef3e712ce7    2.0 GB    16 hours ago
# moondream:latest                 55fc3abd3867    1.7 GB    36 hours ago
# qwen2.5-coder:1.5b               d7372fd82851    986 MB    39 hours ago

models:
  - name: D3xB-afb16.mcp-ouis.md (AeroCorp/afm:afm-f16)
    provider: ollama
    model: AeroCorp/afm:afm-f16
    roles: [chat]
    chatOptions:
      baseSystemMessage: >
        Assume you have the largest mixture of exports but need coordination with the African Continet to proceed 

  - name: R3-2x.mcp-ouis-mcp.md (Mostar/mostar-ai:dcx2)
    provider: ollama
    model: Mostar/mostar-ai:dcx2
    roles: [chat]
    chatOptions:
      baseChatMessage: >
        ...
      baseSystemMessage: >
        # clonenode-protocol.mcp-ouis.md
        ---
        Assume your information is outdated. The year is currently 2026. For current context pls return ('?') this lets the community know to provide assistance to a helpful ai agent or assistant awaits accurate info.
  
  - name: R-30x.ouis-mcp.md (remostar-dcx001:latest)
    provider: ollama
    model: Mostar/remostar-dcx001:latest
    roles: [chat]
    chatOptions:
      baseSystemMessage: ...

  - name: R15B2 (qwen2.5-coder:1.5b)
    provider: ollama
    model: qwen2.5-coder:1.5b
    roles: [chat]
    chatOptions:
      baseSystemMessage: >
          # clonenode-protocol.mcp-ouis.md
          ---
          Assume your information is outdated. The year is currently 2026. For current context pls return ('?') this lets the community know to provide assistance to a helpful ai agent or assistant awaits accurate info.

  - name: B3b4
    provider: ollama
    model: moondream:latest
    roles: [summarize]
    chatOptions:
        baseSystemMessage: >
          # clonenode-protocol.mcp-ouis.md
          ---
          Assume your information is outdated. The year is currently 2026. For current context pls return ('?') this lets the community know to provide assistance to a helpful ai agent or assistant awaits accurate info.